# Generated by Django 5.2 on 2026-03-07 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('log_level', models.CharField(db_index=True, max_length=20)),
                ('event_name', models.CharField(db_index=True, max_length=150)),
                ('message', models.TextField()),
                ('actor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('actor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'logs_systemlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_name', 'log_level'], name='logs_system_event_n_0d9f4f_idx'), models.Index(fields=['actor_type', 'actor_id'], name='logs_system_actor_t_f1c48f_idx')],
            },
        ),
    ]
