# Generated by Django 5.2 on 2026-05-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='actor_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='business_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
