# Generated by Django 5.2 on 2026-05-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_systemlog_actor_email_systemlog_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['created_at'], name='logs_system_created_6d6f8b_idx'),
        ),
    ]
