# Generated by Django 5.2 on 2026-02-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('body_type', models.CharField(choices=[('html', 'HTML'), ('text', 'TEXT')], default='text', max_length=255)),
                ('status', models.CharField(choices=[('sent', 'SENT'), ('failed', 'FAILED'), ('scheduled', 'SCHEDULED')], default='sent', max_length=255)),
                ('schedule_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
