# Generated by Django 5.2 on 2026-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='try_count',
            field=models.IntegerField(default=1),
        ),
    ]
