# Generated by Django 5.2 on 2026-03-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emaillog_bcc_emaillog_try_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='to_email',
            new_name='to_emails',
        ),
    ]
